# v5.18 (Stage 2 first write batch; work order docs/workorders/20261005_v5.18.md r2).
# Every write below is Excel-owned content written once, only while the cell still holds its v5.17 value (same rule as
# gov.gm_update), so a rebuild from v5.18 never overwrites a later Excel edit and the restore log keeps "unmatched 0".
# Seed data comes from gov_seed4.py (generated by tools/gen_seed_v518.py from the review workbook and the v5.17 cells).
#
# Steps (attribution, work order 第 5 節): each value-changing item has a step id. The environment variable V518_STEPS
# (comma list; unset = all; empty = none) switches steps on, so the report can apply C44, C69, D1, … cumulatively and measure
# each increment with LibreOffice. Non-value writes (grades, notes, Gov_Map judgement columns, Decisions) are always on.
import os
from copy import copy
from openpyxl.styles import PatternFill
from common import put, F_IN, F_CALC, F_NOTE, L
import gov_seed4 as S4

ALL_STEPS = ["C44", "C69", "D1", "D3E4", "D4", "E1", "E3", "F1", "G2", "G3", "G4", "RU", "J2", "D5"]

def step_on(step):
    v = os.environ.get("V518_STEPS")
    return True if v is None else step in [s.strip() for s in v.split(",") if s.strip()]

# ------------------------------------------------------------------ formula map (builder-owned links on model pages)
FM_ADD = [("C44", "Train_In!C44", "=SRC_MOD_034/SRC_MOD_040"),
          ("C69", "Calib!C69", "=SRC_HW_019/SRC_HW_040"),
          ("RU", "Spec_Rack!G6", "=SRC_HW_061"),
          ("RU", "Spec_Rack!G28", "=SRC_HW_062"),
          ("E3", "Arch!D16", "=SRC_MOD_054"),
          ("G2", "Spec_Rack!D9", "=SRC_HW_004_Hi")]
FM_DROP = [("G4", "Spec_Rack!F12"), ("RU", "Spec_Rack!G9")]      # become Derived constants (blue inputs), see INPUT_UPD

def formula_map(base):
    fm = dict(base)
    for step, key in FM_DROP:
        if step_on(step): fm.pop(key, None)
    for step, key, f in FM_ADD:
        if step_on(step): fm[key] = f
    return fm

# ------------------------------------------------------------------ model-page inputs (written after restore(); old value is the guard)
INPUT_UPD = [
    ("E1", "Train_In", "C21", 0.8, 1.0),
    ("G3", "Spec_Rack", "E9", 137, 136),
    ("G4", "Spec_Rack", "F11", 6.7, 7.8), ("G4", "Spec_Rack", "F12", "=SRC_HW_015", 8.4),     # r3 I2: F13 stays 9.1
    ("RU", "Spec_Rack", "G8", 550, 300), ("RU", "Spec_Rack", "G9", "=SRC_HW_013", 340), ("RU", "Spec_Rack", "G10", 650, 454),
    ("RU", "Spec_Rack", "G11", 23.4, 11.7), ("RU", "Spec_Rack", "G12", 31.2, 15.6), ("RU", "Spec_Rack", "G13", 39, 19.5),
    ("RU", "Spec_Rack", "G23", 73, 70), ("RU", "Spec_Rack", "G24", 104, 100), ("RU", "Spec_Rack", "G40", 34.7, 35.0),
    ("RU", "Spec_Rack", "G41", 73, 70),                                    # PR #19 審查 3：與 G23 同步（同為 Rubin Ultra NVFP4 訓練 dense）
    # J2（Andy 2026-10-06）：Rubin Ultra 機架價格＝VR200 機架價格（F12，售價口徑 I2）× 1.5／2.0／2.5（倍數 Assumed、價格 Derived）
    ("J2", "Spec_Rack", "G11", 11.7, "=F12*1.5"), ("J2", "Spec_Rack", "G12", 15.6, "=F12*2"), ("J2", "Spec_Rack", "G13", 19.5, "=F12*2.5"),
]
# Labels and notes on the Block 1 part of Spec_Rack (Excel-owned rows 1–19): (cell, old, new), always on
TEXT_UPD = [
    ("G4", "Rubin Ultra NVL576", "Rubin Ultra（MGX NVL 單架，72 GPU）"),
    ("G5", "2027 預估（Kyber）", "2027 預估（NVL576＝8 個單架互連）"),
    ("D15", "約 120–130 kW（S3）；v4＝139", "約 120–132 kW（SemiAnalysis 約 120；HPE QuickSpecs TDP 132 nominal；S3）；基準 132；v4＝139"),
    ("E15", "132–142 kW（S3、S5）", "132–140 kW（wing.vc；S3、S5）；基準 136（區間中點）"),
    ("F15", "Max-Q 約 190、Max-P 約 230 kW（S7）；Supermicro DLC-2 設計點 227 kW（S8）",
     "Max-Q 188、Max-P 227 kW（Schneider Electric 的 NVIDIA VR NVL72 參考設計 MaxQ 188／MaxP 227，2026-05-08；S7）；Supermicro 產品頁 DLC-2 冷卻 sized for 227 kW per rack（SRC_HW_064，口徑不同）"),
    ("F16", "MS $7.8M（自購記憶體 $6.7M）；Bernstein $9.09M；報價 $5–7M（S9）",
     "MS 物料成本 BOM $7.8M（自購記憶體 $6.7M）；Bernstein $9.09M；報價 $5–7M（S9）；v5.18：基準 8.4＝MS BOM 7.8 ×（1＋代工毛利約 7.5%，區間 5–10%，Assumed）；低 7.8（零毛利 BOM 下限）、高 9.1（不變，Bernstein）"),
    ("G14", "144 封裝；價格＝VR 每 GPU 價 × 1.5／2.0／2.5（推估）", "72 封裝（單架）；價格＝VR200 機架價格（F12，售價口徑）× 1.5／2.0／2.5（公式；倍數 Assumed；J2）"),
    ("G15", "約 600 kW（S7）",
     "單架 300／340／454 kW（Derived：低＝舊路線圖 600 kW 依封裝數等比；基準＝72×3.6 kW＋VR 機架非 GPU 功率 61–97 kW 取 340；高＝VR 整架／GPU 功率比值等比；NVIDIA 未公布單架 kW）"),
    ("G17", "Assumed", "Derived／Assumed"),
    ("A19", "註：GPU 數為封裝數（Rubin Ultra 為 144 封裝，NVIDIA 以 576 die 命名為 NVL576）。",
     "註：GPU 數為封裝數。Rubin Ultra 欄為 MGX NVL 單架 72 封裝（NVIDIA 2026-09 技術部落格：NVL576＝8 個單架互連為單一 576-GPU NVLink 域；『GPU』＝封裝為推斷 [Derived]，部落格未明載）；Kyber NVL144 屬 Feynman 世代，不納入。"),
]

def _set_input(ws, cell, val):
    c = ws[cell]
    c.value = val
    if isinstance(val, (int, float)):
        c.font = copy(F_IN); c.fill = PatternFill(fill_type=None)
    elif isinstance(val, str) and val.startswith("="):
        c.font = copy(F_CALC); c.fill = PatternFill(fill_type=None)

def inputs_update(wb):
    """Called after restore() and before gov_all(): numeric inputs (Excel-owned) and Spec_Rack text, each only while at its v5.17 value."""
    log = []
    for step, sh, cell, old, new in INPUT_UPD:
        if not step_on(step): continue
        ws = wb[sh]
        if ws[cell].value == old and type(ws[cell].value) is not bool:
            _set_input(ws, cell, new); log.append(f"{sh}!{cell}: {old!r} -> {new!r} ({step})")
    ws = wb["Spec_Rack"]
    for cell, old, new in TEXT_UPD:
        if ws[cell].value == old:
            ws[cell].value = new; log.append(f"Spec_Rack!{cell}: text updated")
    return log

# ------------------------------------------------------------------ SRC sheets (Excel-owned): field updates with old-value guard
_COL = {k: i + 1 for i, k in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ")}

def _apply(cell, spec):
    if isinstance(spec, (list, tuple)) and spec and spec[0] == "+":
        txt = spec[1]
        cur = cell.value
        if cur in (None, "", "—"):
            cell.value = txt.lstrip("；｜ ")
        elif txt.lstrip("；｜ ") not in str(cur):         # stripped compare: the first write of an empty cell stores the stripped text
            cell.value = f"{cur}{txt}"
        else: return False
        return True
    old, new = spec
    if cell.value == old:
        cell.value = new; return True
    return False

def src_update(wb):
    n = 0; log = []
    for sid, d in S4.SRC_UPD.items():
        if d["step"] and not step_on(d["step"]): continue
        ws = wb[d["sheet"]]
        row = next((r for r in range(5, ws.max_row + 1) if ws.cell(r, 1).value == sid), None)
        if row is None: log.append(f"{sid}: record not found"); continue
        for col, spec in d["fields"].items():
            if _apply(ws[f"{col}{row}"], spec): n += 1
            else: log.append(f"{sid}!{col}: kept (not at v5.17 value or already applied)")
    return n, log

# ------------------------------------------------------------------ Gov_Map judgement columns (Excel-owned A–P)
_N = "N"
def _G(sheet, cell, **cols): return (sheet, cell, cols)
GOV_UPD = [
    _G("Spec_Rack", "G6", H=("SRC_HW_054", "SRC_HW_061")),
    _G("Spec_Rack", "G28", H=("SRC_HW_054", "SRC_HW_062"), K=(None, 72), L=(None, 576),
       M=("—", "低 72＝單架內全互連；高 576＝NVL576 兩層 NVLink 域（v5.18）")),
    _G("Spec_Rack", "G8", F=("Assumed", "Derived"), N=("Rubin Ultra 為推估欄（D2），不進基準比較；600 kW ± 50", "v5.18 RU：300＝舊路線圖 600 kW × 72/144（每封裝功率等比）[Derived]；NVIDIA 未公布單架 kW")),
    _G("Spec_Rack", "G9", F=("原始數據", "Derived"), G=("單值", "基準"), H=("SRC_HW_013", "—"), I=("直接", "換算（72×3.6 kW GPU＋VR 機架非 GPU 功率 61–97 kW → 320–357，取 340）"),
       K=(None, "=Spec_Rack!G8"), L=(None, "=Spec_Rack!G10"),
       N=("連結 SRC（G1）", "v5.18 RU：基準 340＝72×3.6 kW ＋ (227 − 72×1.8–2.3 kW)＝320–357 取 340 [Derived]；SRC_HW_013（單架 600 kW）已 Superseded"),
       O=("—", "原始數據→Derived（v5.18 RU）")),
    _G("Spec_Rack", "G10", F=("Assumed", "Derived"), N=("Rubin Ultra 為推估欄（D2），不進基準比較；600 kW ± 50", "v5.18 RU：454＝259 kW（72×3.6）× VR 整架／GPU 功率比值 227/(72×1.8)＝1.75 [Derived／Analogy]")),
    _G("Spec_Rack", "G11", N=("Rubin Ultra 為推估欄（D2），不進基準比較；VR 每 GPU 價 × 1.5", "v5.18 J2：VR200 機架價格（售價口徑，I2）× 1.5；公式 =F12*1.5＝12.6（倍數 Assumed、價格 Derived）"),
       O=("—", "Assumed（倍數）＋Derived（以 F12 為底；v5.18 J2）")),
    _G("Spec_Rack", "G12", N=("Rubin Ultra 為推估欄（D2），不進基準比較；VR 每 GPU 價 × 2.0", "v5.18 J2：VR200 機架價格（售價口徑，I2）× 1.5／2.0／2.5；G12 公式 =F12*2＝16.8（倍數 Assumed、價格 Derived）；Rubin Ultra 尚未定價，無外部報價（DB_Evidence 已記查詢詞）"),
       O=("—", "Assumed（倍數）＋Derived（以 F12 為底；v5.18 J2）")),
    _G("Spec_Rack", "G13", N=("Rubin Ultra 為推估欄（D2），不進基準比較；VR 每 GPU 價 × 2.5", "v5.18 J2：VR200 機架價格（售價口徑，I2）× 2.5；公式 =F12*2.5＝21.0（倍數 Assumed、價格 Derived）"),
       O=("—", "Assumed（倍數）＋Derived（以 F12 為底；v5.18 J2）")),
    _G("Spec_Rack", "G23", F=("Assumed", "Derived"), H=("—", "SRC_HW_063"), I=("—", "Derived：2 × VR NVFP4 訓練 dense 35（2,520 PF ÷ 72，註 Dense）＝70；Rubin Ultra 4 die 對 Rubin 2 die"),
       N=("Rubin Ultra 為推估欄（D2），不進基準比較", "v5.18 RU：70＝2 × 35 [Derived]；NVIDIA 未直接公布 Rubin Ultra 每封裝 NVFP4 dense"), O=("—", "Assumed→Derived（v5.18 RU）")),
    _G("Spec_Rack", "G24", F=("原始數據（G0-2 保留）", "Derived"), H=("SRC_HW_031", "SRC_HW_063"), I=("取整（15,000 ÷ 144＝104.2 → 104）", "Derived：2 × VR NVFP4 推論 50（Sparse；3,600 PF ÷ 72）＝100"),
       N=("值與來源不等（取整（15,000 ÷ 144＝104.2 → 104））：Stage 1 保留藍字，Stage 2 逐筆決定（G0-2）", "v5.18 RU：100＝2 × 50 [Derived]；SRC_HW_031（15 EF ÷ 144＝104）屬 Kyber 舊路線圖，差 4%"),
       O=("—", "原始數據（G0-2 保留）→Derived（v5.18 RU）")),
    _G("Spec_Rack", "G40", F=("原始數據（G0-2 保留）", "Derived"), H=("SRC_HW_045", "SRC_HW_063"), I=("取整（5,000 ÷ 144＝34.72 → 34.7）", "Derived：2 × VR FP8/FP6 訓練 dense 17.5（1,260 PF ÷ 72，註 Dense）＝35.0"),
       N=("值與來源不等（取整（5,000 ÷ 144＝34.72 → 34.7））：Stage 1 保留藍字，Stage 2 逐筆決定（G0-2）", "v5.18 RU：35.0＝2 × 17.5 [Derived]；SRC_HW_045（5,000 PF 整機）Superseded"),
       O=("—", "原始數據（G0-2 保留）→Derived（v5.18 RU）")),
    _G("Spec_Rack", "F11", F=("原始數據（G0-2 保留）", "Derived"), H=("SRC_HW_016", "SRC_HW_015"),
       I=("來源為 Alt（G13 多家獨立估計，Stage 2 決定）", "Derived：MS BOM 7.8（零毛利下限；r3 I2）"),
       N=("值與來源不等（來源為 Alt（G13 多家獨立估計，Stage 2 決定））：Stage 1 保留藍字，Stage 2 逐筆決定（G0-2）", "v5.18 G4／I2：低 7.8＝MS BOM（零毛利下限；BOM 本身為分析師估計，區間保留其不確定）；原 6.7（SRC_HW_016）不再連結"),
       O=("—", "原始數據（G0-2 保留）→Derived（v5.18 G4）")),
    _G("Spec_Rack", "F12", F=("原始數據", "Derived"), G=("單值", "基準"), I=("直接", "Derived：MS BOM 7.8 ×（1＋代工毛利 7.5%，Assumed）＝8.4"),
       K=(None, "=Spec_Rack!F11"), L=(None, "=Spec_Rack!F13"),
       N=("連結 SRC（G1）", "v5.18 G4：基準 8.4＝7.8 × (1＋7.5%)；7.8 為 Morgan Stanley 成本（BOM），不是售價，差距以代工毛利假設補（Assumed，區間 5–10%）；低 7.8、高 9.1"),
       O=("—", "原始數據→Derived（v5.18 G4）")),
    _G("Spec_Rack", "D9", F=("原始數據（G0-2 保留）", "原始數據"), I=("選取（區間上緣 130）", "直接（SRC_HW_004 上緣 132；HPE QuickSpecs V6 TDP 132 kW nominal）"),
       N=("值與來源不等（選取（區間上緣 130））：Stage 1 保留藍字，Stage 2 逐筆決定（G0-2）", "v5.18 G2：基準 132＝SRC_HW_004 上緣（連結）；低 120（SemiAnalysis）；高 140 為 Assumed")),
    _G("Spec_Rack", "E9", F=("原始數據（G0-2 保留）", "Derived"), I=("區間中點", "Derived：區間中點 (132＋140)/2＝136"),
       N=("值與來源不等（區間中點）：Stage 1 保留藍字，Stage 2 逐筆決定（G0-2）", "v5.18 G3：基準 136＝SRC_HW_005 區間 132–140（wing.vc）中點 [Derived]"),
       O=("—", "原始數據（G0-2 保留）→Derived（v5.18 G3）")),
    _G("Calib", "C69", F=("Derived（待改公式）", "Derived（公式）"), I=("—", "換算（SRC_HW_019 ÷ SRC_HW_040＝0.989 ÷ 1.979＝0.49975）"),
       N=("v5.5 峰值更正（989→1,979 TF）後維持產出不變的換算（≈989÷1,979＝0.4997，模型取 0.5）；不確定性由 Calib C5 η_p 區間承擔，不另給區間；改公式會改值（G0-2），Stage 2",
          "v5.18 C69：改為公式 =SRC_HW_019/SRC_HW_040（0.49975）；不確定性仍由 Calib C5 η_p 區間承擔，不另給區間")),
    _G("Train_In", "C44", F=("Derived（待改公式）", "Derived（公式）"),
       N=("改公式會使值 0.055→0.0552（G0-2）；Stage 2 處理", "v5.18 C44：改為公式 =SRC_MOD_034/SRC_MOD_040（0.05518）；所有輸出影響 0")),
    _G("Calib", "C17", I=("直接", "直接（內插值 9,342.1，Derived；H1 規則 2 級；W1 待第二來源）"), O=("—", "v5.18 D1：9,384.4→9,342.1（內插式見 SRC_PERF_009）")),
    _G("Calib", "D17", I=("直接", "直接（內插值 3,405.2，Derived；H1 規則 2 級；W1 待第二來源）"), O=("—", "v5.18 D1：3,473.9→3,405.2（內插式見 SRC_PERF_010）")),
    _G("Train_In", "C21:G21", M=("各世代 ±0.2（Claude 提議，Andy 2026-10-03 確認）", "各世代 ±0.2（Claude 提議，Andy 2026-10-03 確認）；v5.18 E1：Hopper（C21）基準 0.8→1.0，區間 0.8–1.2（Assumed）"),
       N=("預訓練 MFU 世代倍數；Hopper 0.8 使 MFU＝20%，對應 DeepSeek V3 推導值（SRC_MOD_040 等）；VR200 峰值增幅大於 HBM 頻寬增幅",
          "預訓練 MFU 世代倍數；v5.18 E1：Hopper 基準 1.0（原 0.8 使 MFU＝20%，對應 DeepSeek V3 推導值）；MegaScale-MoE 方向性證據（MFU 隨 GPU 運算能力下降）與現行倍數相反，已讀未採用，列待判斷")),
    _G("Arch", "C34:D34", K=(None, 4), L=(None, 130),
       M=("4–128 B（全 HCA 128× 至全 CSA 4× 的每層 KV；Claude 提議，Andy 2026-10-03 確認）", "4–130 B（全 HCA 128× 至全 CSA 4× 的每層 KV；v5.18 D3／E4：高 130＝bf16 KV、涵蓋 indexer key 情境；基準 65 不動）"),
       N=("Luna／Sol 每層 KV bytes 65＝v4 推導值；V4 官方 config（KV head 512、CSA 4×、HCA 128×、滑動窗 128）可結構重算，但會改值（Stage 2）",
          "Luna／Sol 每層 KV bytes 65＝v4 推導值；B5 結構重算（只計壓縮 KV）Flash 64.37／Pro 64.98，與 65 相差 <1.1%；計入 indexer key 80.0／80.7；bf16 KV 128.7／130.0（參考程式預設 dtype；生產精度未找到出處）")),
    _G("Serving", "D23", L=("=Serving!D23*2", 68000)), _G("Serving", "E23", L=("=Serving!E23*2", 68000)),
]
# D5 notes appended to the reason column (evidence IDs come from the seed): (sheet, cell, text)
def _d5_notes():
    ev = S4.EV
    return [("Serving", c, f" ｜v5.18 D5（r3 I1）：區間高擴至 68,000 以涵蓋 Copilot 每呼叫提示中位（{ev['ISL']}；Analogy）；基準不動；C23（Luna）不套用") for c in ("D23", "E23")] + \
           [("Workload", c, f" ｜v5.18 r3 I1：區間不改，Copilot 追蹤已讀且已涵蓋（{ev['T']}；單位對應見該列）") for c in ("G5",)] + \
           [("Workload", c, f" ｜v5.18 r3 I1：區間不改，已涵蓋 Copilot 加權命中約 0.90（{ev['CHI']}）；E:G 與 DeepSeek 56.3%（{ev['CHI2']}，C:D）") for c in ("E11",)]

def _append_text(cell, txt):
    cur = cell.value
    if cur in (None, ""): cell.value = txt.lstrip(" ｜"); return True
    if isinstance(cur, str) and txt.lstrip(" ｜") in cur: return False
    if isinstance(cur, str) and cur.startswith("="):
        cell.value = cur + '&"' + txt.replace('"', '""') + '"'; return True
    cell.value = f"{cur}{txt}"; return True

def gov_update(ws):
    """Gov_Map A–P judgement updates (old-value guard) plus the B-method 'O＋L1' segment column (P) and IF-wide supplementary flags."""
    loc = {(ws[f"C{r}"].value, ws[f"D{r}"].value): r for r in range(5, ws.max_row + 1) if ws[f"C{r}"].value}
    n = 0
    for sh, cell, cols in GOV_UPD:
        r = loc.get((sh, cell))
        if r is None: continue
        for col, (old, new) in cols.items():
            c = ws[f"{col}{r}"]
            if c.value == old:
                c.value = new; n += 1
    for sh, cell, txt in _d5_notes():
        r = loc.get((sh, cell))
        if r is not None and _append_text(ws[f"N{r}"], txt): n += 1
    # P: B-method segment ('O＋L1'); Inputs!E5 is 無 per the work order
    for sh, cell, old, new in S4.P_UPD:
        r = loc.get((sh, cell))
        if r is not None and ws[f"P{r}"].value == old:
            ws[f"P{r}"].value = new; n += 1
    # IF-wide segment: supplementary flag in the reason column (not used as the segment basis)
    for key, seg in S4.IF_FLAG.items():
        sh, cell = key.split("|", 1)
        r = loc.get((sh, cell))
        if r is not None and _append_text(ws[f"N{r}"], f" ｜補充旗標（IF 全欄分段，非分段依據）：{seg}"): n += 1
    return n

# ------------------------------------------------------------------ DB_Evidence, Decisions, new SRC records (appended by gov.py loops)
def src_new_records():
    return S4.NEWREC

def evidence_rows():
    rows = [list(r) for r in S4.EVID_MIG4]
    return rows

def decisions_rows():
    return S4.DEC
